FROM oven/bun:1
WORKDIR /user/src/app
COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./bun.lock ./bun-lock
COPY ./apps/http ./apps/http
RUN bun i
RUN bun run db:generate 
EXPOSE 3000
CMD ["bun","run","index.ts"]